"""Add course_subject, course_number, instructor, and grade columns to grade_distribution

Revision ID: 6432283cf6af
Revises: e3c6c3bcf597
Create Date: 2024-12-18 18:58:30.621266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6432283cf6af'
down_revision = 'e3c6c3bcf597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_distribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_subject', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('course_number', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('instructor', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('grade_a', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grade_b', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grade_c', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grade_d', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('grade_f', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grade_distribution', schema=None) as batch_op:
        batch_op.drop_column('grade_f')
        batch_op.drop_column('grade_d')
        batch_op.drop_column('grade_c')
        batch_op.drop_column('grade_b')
        batch_op.drop_column('grade_a')
        batch_op.drop_column('instructor')
        batch_op.drop_column('course_number')
        batch_op.drop_column('course_subject')

    # ### end Alembic commands ###
